# $FreeBSD$

PACKAGE=	tests

TESTSDIR=       ${TESTSBASE}/sys/netinet6/regress

ATF_TESTS_SH+=	fragmentation

${PACKAGE}FILES+=	utils.subr \
			echo_inetd.conf \

#${PACKAGE}FILESMODE_pft_ping.py=	0555

.include <bsd.test.mk>
