# $FreeBSD$

PACKAGE=        tests

TESTSDIR=       ${TESTSBASE}/sys/netinet6/ipv6/regress/frag6

${PACKAGE}FILES+=	frag6.py \
                        frag6_ext.py \
                        frag6_hop.py \
                        frag6_maxlen.py \
                        frag6_mf0atomic.py \
                        frag6_mf0long.py \
                        frag6_mf0middle.py \
                        frag6_mf0short.py \
                        frag6_mf1end.py \
                        frag6_opt.py \
                        frag6_overatomic.py \
                        frag6_overdrop.py \
                        frag6_overhead.py \
                        frag6_overhead0.py \
                        frag6_overhead1.py \
                        frag6_overtail.py \
                        frag6_overtail0.py \
                        frag6_overtail1.py \
                        frag6_padding.py \
                        frag6_permute.py \
                        frag6_queuelimit.py \
                        frag6_refrag.py \
                        frag6_shortatomic.py \
                        frag6_timeout.py \
                        frag6_udpatomic.py \
                        frag6_udpheader.py \
                        frag6_udppayload.py \
                        frag6_zerofirst.py \
                        frag6_zerosecond.py
.include <bsd.test.mk>

